config action icons
phuhl/linux_notification_center pull request #116
Opened 2020-12-14 15:12 UTC by ahmubashshir

- Add config file option for Action Icons.

2020-12-19 17:09 UTC, phuhl requested changes
Thanks for the PR, there seems to be an issue though, that prevents this from building. Also, please update the readme so, the new feature is accessible to everybody :)

2020-12-19 17:09 UTC, phuhl commented on src/NotificationCenter/Notifications/Action.hs
> +  if useIcons And configActionIcons config then do
This fails to build on my machine

2020-12-19 17:09 UTC, phuhl commented on src/NotificationCenter/Notifications/Action.hs
> +  if useIcons And configActionIcons config then do
```suggestion
  if useIcons and configActionIcons config then do
```

2020-12-20 07:17 UTC, ahmubashshir commented on src/NotificationCenter/Notifications/Action.hs
> +  if useIcons And configActionIcons config then do
fixed :3

2020-12-23 14:21 UTC, phuhl requested changes
Did you try to compile this? It doesn't on my machine. I can't merge it like this. Also, still the documentation is missing.

2020-12-23 14:32 UTC, ahmubashshir commented
> Did you try to compile this? It doesn't on my machine. I can't merge it like this. Also, still the documentation is missing.

Sorry :3 I forgot write doc.

2020-12-24 04:24 UTC, ahmubashshir commented
Fixed it 🐱 Haskell didn't actually use `And` or `and` for logical and, 😅 Instead, it used `&&` for it 😌
And I update docs too ☺️

2021-01-13 08:58 UTC, merged